### ISSUE TITLE
[Feature]: Meta LlamaStack Support

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/agentops#488]
### 💡 Feature Description and Proposed Solution

https://github.com/meta-llama/llama-stack-client-python

Meta created an agent framework called LlamaStack. We should:
1. Try to raise a PR to add optional AgentOps support for tracking
2. Add auto-instrumentation in the AgentOps library to integrate with Llama Stack

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

**Comment by thaddavis** [comment]
I'm working on this
