### ISSUE TITLE
Integrate `black` and `ruff` with pre-commit hooks in the CI

### ISSUE THREAD

**Issue by dot-agi** [AgentOps-AI/agentops#509]
### 💡 Feature Description and Proposed Solution

`black` and `ruff` are for linting the code to adhere to PEP-8 format and type checks.

Using pre-commit hooks will allow us more flexibility in the rules that it should respect when linting our codebase.

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.
