### ISSUE TITLE
[idea]: UI revamp proposal towards better UX

### ISSUE THREAD

**Issue by teocns** [AgentOps-AI/agentops#512]
### 💡 Feature Description and Proposed Solution

https://ui.shadcn.com/

I think the UI is the most important aspect of the product. Let's make a plan on the effort required to get there, if there's positive feedback around the idea

### 🤝 Contribution

- [X] Yes, I'd be happy to submit a pull request with these changes.
- [X] I need some guidance on how to contribute.
- [X] I'd prefer the AgentOps team to handle this update.

**Comment by areibman** [comment]
> 

The AgentOps frontend is already using shadcn :) If you have any specific components in mind let us know though 

cc @ddtch
